server:
  port: 60000
  servlet:
    context-path: /quartzApi

spring:
  profiles:
    active: loc
  application:
    name: iQuartzService
  # 数据库信息配置
  datasource:
    name: rcms_tmdb
    url: jdbc:mysql://127.0.0.1:3306/rcms_tmdb
    username: root
    password: max@756423
    driver-class-name: com.mysql.jdbc.Driver

# 指定日志文件
logging:
  config: classpath:log4j2.xml

# mybatis 配置
mybatis:
  # mybatis sql 文件扫描路径
  mapper-locations: classpath*:com/stone/it/**/dao/*.mysql.xml
  # 指定实体类的路径
  type-aliases-package: com.stone.it.**.vo
